apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nyznoprfp-go 
  janus-idp.io/tekton: nyznoprfp-go
  backstage.io/kubernetes-id: nyznoprfp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nyznoprfp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml