apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nyznoprfp-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:1047bda20bc0d9ac239707eb7edbcd5bb09f5b74@sha256:bccca59d60a3da2e67d3cc51a503854547c3ce893ae5c138559b74b5c6534a9f
          name: container-image
